export class personData
{
    referenceNumber: string;
    church: string;
    name: string;
    maritalState: string;
    createdDate: Date;
    lastModified: Date;
    emirateId: string;
    birthDate: Date;
    placeOfBirth: string;
    baptismDate: Date;
    placeOfBaptism: string;
    edQualification: string;
    educationDate: Date;
    address: string;
    jobTitle: string;
    jobAddress: string;
    militaryStatus: string ;
    relatedChurch: string;
    confessoPriest:string;
    confessorChurch :string;
    confessionRate: string;
    eucharistRate: string;
    foreignCountryName: string;
    foreignCountryDate: Date;
    familyLinks : string;
    engagedBefore: string;
    marriedOutside: string;
    marriedInside: string;
    churchMarriage: string;
    marriagePlace: string;
    marriagePriest: string;
    civilMarriage : string;
    civilMarriageDate: Date;
    maritalStatus: string;
    widowhoodDate: Date;
    marriedBeforeWidowhood: string;
    marriageBeforeWidowhoodInfo: string;
    divorced: string;
    court: string;
    caseNum: string;
    caseDate: Date;
    marriageApprovalSource: string;
    marriageApprovalDate: Date;
    childsNum: string;
    childAge: string;
    childsBiptesm: string;
    hasChildren:string;
    hasSecondClearance: string;
    marriedBefore: string;
    marriageType: string;
    status: string;
    graduateDate: Date;
    recognitionRegularityRate:string;
    intakeRate:string;
    fatherOfConfession:string;
    gender:string;
    churchId:number;
    userId:number;
    engageDate: Date;
    mariageStatus:string;
    socialStatus:string;
    sourceOfPermitMarriage:string;   
    dateOfPermitMarriage:Date;
}